@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 25 01:13:04 +0200 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim project_tb_ms_func_synth -key {Post-Synthesis:sim_2:Functional:project_tb_ms} -tclbatch project_tb_ms.tcl -log simulate.log"
call xsim  project_tb_ms_func_synth -key {Post-Synthesis:sim_2:Functional:project_tb_ms} -tclbatch project_tb_ms.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
